### ISSUE TITLE
The AbstractHibernateDAO should be modified to abstract class

### ISSUE THREAD

**Issue by koropatva** [koropatva/MyWay#28]
Main task of the AbstractHibernateDAO is to be a base for all other services. In the name of the class it calls abstract, but in real it is a simple class that can be created. We should rewrite it, as we can have some issue in the future. The class should be abstract and calls _HibernateDAO_

**Comment by Man4ester** [comment]
better to stay name Abstract in name of class. it will be more easy to understand main goal of class

**Comment by koropatva** [comment]
ok, call then PrincipleHibernateDAO or BaseHibernateDAO. It is more readable. Abstract - it is very abstract name for the class
