### ISSUE TITLE
ModifiedTime and creationTime should be filled in the MySQL

### ISSUE THREAD

**Issue by koropatva** [koropatva/MyWay#36]
CreationTime and ModifiedTime should be filled in the database and not from the code. We should modified DB structure and code for new modifications

**Comment by Man4ester** [comment]
i created 2 triggers for block table. I think it is good solution. What you think about this. If you agree with this approach i wll do the same for all table with this fields (creation and modified dateTime)

**Comment by koropatva** [comment]
approved
