### ISSUE TITLE
Remove save method from BaseHibernateDAO

### ISSUE THREAD

**Issue by koropatva** [koropatva/MyWay#37]
save method is not clear. In the BaseHibernateDAO we have create and update methods, it's not clear why and for what we need save method?

**Comment by Man4ester** [comment]
we have difference 
1. create use persist
2. update use merge
3. save use general saveOrUpdate

if you will use update for new Entity(not saved in DB Transient ) you will have error
if you will use create for Persistent  Entity you will have error

in general we can use saveOrUpdate but it is almost more slow than other. This method in general always will decide what to use persist or merge

**Comment by koropatva** [comment]
DAO is a base class and for me as developer it doesn't matter, how it is realized. For me is most important to know that when I call update it will update my modifications, when I call create it will create new record. So, when I should call save? It is redundant method.

P.S. I know, it uses a difference logic under the hood, but I as developer don't know in what situation I should call save?

**Comment by koropatva** [comment]
In general a method should do one simple action, and when we have a method with  saveOrUpdate name, we can't control the logic of this method. We should avoid it
