### ISSUE TITLE
Need to develop parser for http://www.turystam.in.ua/ site

### ISSUE THREAD

**Issue by koropatva** [koropatva/MyWay#4]
http://www.turystam.in.ua/ site contains a lot of interesting information for our project. Needs to develop a parser to copy and save data in our system 

1 try to get from google all inforation by id and locations
2 If goole doesn't return result need to parse all information from source site
3 Must be separate application
4 Store in separate DB

**Comment by Man4ester** [comment]
link for source: https://github.com/Man4ester/MyWayParser

**Comment by Man4ester** [comment]
done
